---

linux:
  type: command
  when: "{{ system == 'Linux' }}"
  command: |
    wget https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip -O /tmp/terraform.zip
    unzip -o /tmp/terraform.zip -d /tmp/
    sudo mv /tmp/terraform /usr/local/bin/terraform2
    echo 'Done installing terraform'

mac:
  type: command
  when: "{{ system == 'Darwin' }}"
  command: brew install terraform
  