---

linux:
  type: command
  when: "{{ system == 'Linux' }}"
  command: |
    wget https://releases.hashicorp.com/packer/1.4.4/packer_1.4.4_linux_amd64.zip -O /tmp/packer.zip
    unzip -o /tmp/packer.zip -d /tmp/
    sudo mv /tmp/packer /usr/local/bin

mac:
  type: command
  when: "{{ system == 'Darwin' }}"
  command: brew install packer
  